image_path: ./assets/gcp-logo.png
project_id: project-demo-389821
region: us-central1
prompt_palm_improvement:  |
    """ 
        This is a podcast transcription
    
        Podcast Text: {}

    """