image_path: ./assets/pi.jpg
project_id: project-demo-389821
region: us-central1
prompt_palm_improvement:  |
    """ 
        Enriquece y extiende la descripcion recibida con los attributos que se te dan, epieza por. Genera un pie de foto de 300 caracteres y muestralo en catalan y español. 
    
        description: {}
        attributes: {} , {}

    """